server:
  port: 18081

spring:
  application:
    name: oauth-server   # 应用名称

  jpa:
      open-in-view: true
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
  # 数据源 配置
  datasource:
      platform: postgres
      url: jdbc:postgresql://101.132.136.225:5432/cloud_oauth2
      username: postgres
      password: postgres123
      driver-class-name: org.postgresql.Driver

  # redis 配置
  redis:
    host: 101.132.136.225
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 1000ms


logging:
  level:
    org:
      springframework:
        security: DEBUG